apiVersion: v1

kind: Service

metadata:
  name: k8s-demo-fastapi 

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: k8s-demo-fastapi  # The selector.app should match the labels.app of the Pod
    release: "1.0.1"  # The selector.release should match the labels.release of the Pod

  ports:
    - name: http
      nodePort: 30000
      port: 8080
      targetPort: 8080
  
  type: NodePort
